# Generated by Django 4.0.4 on 2022-05-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Id de la categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la marca')),
                ('nombreMarca', models.CharField(max_length=50, verbose_name='Nombre de la marca')),
                ('estadoSubcategoria', models.PositiveSmallIntegerField(verbose_name='Estado de la marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='SKU del producto')),
                ('nombreProducto', models.CharField(max_length=75, verbose_name='Nombre del producto')),
                ('imagenProducto', models.FileField(upload_to='', verbose_name='Imagen del producto')),
                ('fechaLanProducto', models.DateField(verbose_name='Fecha de lanzamiento del producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del producto')),
                ('estadoProducto', models.PositiveSmallIntegerField(verbose_name='Estado del producto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('idSuscriptor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del suscriptor')),
                ('emailSuscriptor', models.CharField(max_length=100, verbose_name='Email del suscriptor')),
                ('estadoSuscriptor', models.PositiveSmallIntegerField(verbose_name='Estado del suscriptor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('emailUsuario', models.CharField(max_length=100, verbose_name='Email del usuario')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
                ('apellidoUsuario', models.CharField(max_length=50, verbose_name='Apellido del usuario')),
                ('contrasena', models.CharField(max_length=20, verbose_name='Contraseña del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('idUnidad', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='UPC de la unidad')),
                ('fechaIngUnidad', models.DateField(verbose_name='Fecha de ingreso de la unidad')),
                ('estadoUnidad', models.PositiveSmallIntegerField(verbose_name='Estado de la unidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('idSubcategoria', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id de la subcategoría')),
                ('nombreSubcategoria', models.CharField(max_length=50, verbose_name='Nombre de la subcategoría')),
                ('estadoSubcategoria', models.PositiveSmallIntegerField(verbose_name='Estado de la subcategoría')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategoria'),
        ),
    ]
