# Generated by Django 4.0.4 on 2022-05-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='contrasenaUsuario',
        ),
        migrations.AlterField(
            model_name='marca',
            name='estadoSubcategoria',
            field=models.IntegerField(verbose_name='Estado de la marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estadoProducto',
            field=models.IntegerField(verbose_name='Estado del producto'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='estadoSubcategoria',
            field=models.IntegerField(verbose_name='Estado de la subcategoría'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='estadoSuscriptor',
            field=models.IntegerField(verbose_name='Estado del suscriptor'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='estadoUnidad',
            field=models.IntegerField(verbose_name='Estado de la unidad'),
        ),
    ]
