# Generated by Django 4.0.4 on 2022-05-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_contrasena_usuario_contrasenausuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='estadoSubcategoria',
            new_name='estadoMarca',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(upload_to='', verbose_name='Imagen del producto'),
        ),
    ]
