# Generated by Django 4.0.4 on 2022-05-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Suscriptor',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
