# Generated by Django 4.0.4 on 2022-05-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(upload_to='products/media', verbose_name='Imagen del producto'),
        ),
    ]
