# Generated by Django 4.0.4 on 2022-05-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_producto_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='idSuscriptor',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id del suscriptor'),
        ),
    ]
