# Generated by Django 4.0.4 on 2022-05-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_suscriptor_idsuscriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='estadoMarca',
            field=models.IntegerField(default=1, verbose_name='Estado de la marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estadoProducto',
            field=models.IntegerField(default=1, verbose_name='Estado del producto'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='estadoSubcategoria',
            field=models.IntegerField(default=1, verbose_name='Estado de la subcategoría'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='estadoSuscriptor',
            field=models.IntegerField(default=1, verbose_name='Estado del suscriptor'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='estadoUnidad',
            field=models.IntegerField(default=1, verbose_name='Estado de la unidad'),
        ),
    ]
