# Generated by Django 4.0.4 on 2022-05-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_marca_estadomarca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='emailSuscriptor',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email del suscriptor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='emailUsuario',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id del usuario'),
        ),
    ]
