# Generated by Django 4.0.4 on 2022-05-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_suscriptor_emailsuscriptor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
