# Generated by Django 4.0.4 on 2022-05-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='estadoMarca',
            field=models.IntegerField(default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='idMarca',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombreMarca',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='idPlataforma',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nombrePlataforma',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estadoProducto',
            field=models.IntegerField(default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaLanProducto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(upload_to='products/media', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=75, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='estadoSubcategoria',
            field=models.IntegerField(default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='idSubcategoria',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombreSubcategoria',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='emailSuscriptor',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='estadoSuscriptor',
            field=models.IntegerField(default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='idSuscriptor',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='estadoUnidad',
            field=models.IntegerField(default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='fechaIngUnidad',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='idUnidad',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='UPC'),
        ),
    ]
