# Generated by Django 4.0.4 on 2023-05-28 04:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreMarca', models.CharField(max_length=50, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombreProducto', models.CharField(max_length=75, verbose_name='Nombre')),
                ('imagenProducto', pyuploadcare.dj.models.ImageField(blank=True, verbose_name='Imagen')),
                ('fechaLanProducto', models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento')),
                ('precioProducto', models.IntegerField(verbose_name='Precio')),
                ('descripcionProducto', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('modeloProducto', models.CharField(max_length=50, verbose_name='Modelo')),
                ('colorProducto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('idUnidad', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='UPC')),
                ('fechaIngUnidad', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('idSubcategoria', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreSubcategoria', models.CharField(max_length=50, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoria', verbose_name='Categoría')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategoria', verbose_name='Subcategoría'),
        ),
    ]
